"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AUTH_REFRESH_TOKEN_INVALID = exports.AUTH_REFRESH_TOKEN_MISSING = exports.AUTH_INVALID_CREDENTIALS = exports.AUTH_EMAIL_CONFLICT = exports.AUTH_ERROR_CODES = void 0;
exports.AUTH_ERROR_CODES = {
    EMAIL_CONFLICT: "AUTH_EMAIL_CONFLICT",
    INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    REFRESH_TOKEN_MISSING: "AUTH_REFRESH_TOKEN_MISSING",
    REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
};
exports.AUTH_EMAIL_CONFLICT = exports.AUTH_ERROR_CODES.EMAIL_CONFLICT;
exports.AUTH_INVALID_CREDENTIALS = exports.AUTH_ERROR_CODES.INVALID_CREDENTIALS;
exports.AUTH_REFRESH_TOKEN_MISSING = exports.AUTH_ERROR_CODES.REFRESH_TOKEN_MISSING;
exports.AUTH_REFRESH_TOKEN_INVALID = exports.AUTH_ERROR_CODES.REFRESH_TOKEN_INVALID;
