export declare const AUTH_ERROR_CODES: {
    readonly EMAIL_CONFLICT: "AUTH_EMAIL_CONFLICT";
    readonly INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS";
    readonly REFRESH_TOKEN_MISSING: "AUTH_REFRESH_TOKEN_MISSING";
    readonly REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID";
};
export declare const AUTH_EMAIL_CONFLICT: "AUTH_EMAIL_CONFLICT";
export declare const AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS";
export declare const AUTH_REFRESH_TOKEN_MISSING: "AUTH_REFRESH_TOKEN_MISSING";
export declare const AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID";
export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
