import { GATEWAY_EVENT_PATTERNS, TASK_FORWARDING_PATTERNS } from '@repo/types';

export {
  NOTIFICATIONS_GATEWAY_CLIENT,
  NOTIFICATIONS_GATEWAY_QUEUE,
  NOTIFICATIONS_RPC_QUEUE,
  NOTIFICATIONS_MESSAGE_PATTERNS,
  TASKS_EVENTS_QUEUE,
  TASK_FORWARDING_PATTERNS,
  GATEWAY_EVENT_PATTERNS,
} from '@repo/types';

export const COMMENT_NEW_EVENT = GATEWAY_EVENT_PATTERNS.COMMENT_NEW;
export const TASK_CREATED_EVENT = GATEWAY_EVENT_PATTERNS.TASK_CREATED;
export const TASK_UPDATED_EVENT = GATEWAY_EVENT_PATTERNS.TASK_UPDATED;
export const TASK_DELETED_EVENT = GATEWAY_EVENT_PATTERNS.TASK_DELETED;

export const TASKS_COMMENT_CREATED_PATTERN =
  TASK_FORWARDING_PATTERNS.COMMENT_CREATED;
export const TASKS_CREATED_PATTERN = TASK_FORWARDING_PATTERNS.CREATED;
export const TASKS_UPDATED_PATTERN = TASK_FORWARDING_PATTERNS.UPDATED;
export const TASKS_DELETED_PATTERN = TASK_FORWARDING_PATTERNS.DELETED;
