export const AUTH_ERROR_CODES = {
  EMAIL_CONFLICT: "AUTH_EMAIL_CONFLICT",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  REFRESH_TOKEN_MISSING: "AUTH_REFRESH_TOKEN_MISSING",
  REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
