export const AUTH_ERROR_CODES = {
  EMAIL_CONFLICT: "AUTH_EMAIL_CONFLICT",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  REFRESH_TOKEN_MISSING: "AUTH_REFRESH_TOKEN_MISSING",
  REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
} as const;

export const AUTH_EMAIL_CONFLICT = AUTH_ERROR_CODES.EMAIL_CONFLICT;
export const AUTH_INVALID_CREDENTIALS =
  AUTH_ERROR_CODES.INVALID_CREDENTIALS;
export const AUTH_REFRESH_TOKEN_MISSING =
  AUTH_ERROR_CODES.REFRESH_TOKEN_MISSING;
export const AUTH_REFRESH_TOKEN_INVALID =
  AUTH_ERROR_CODES.REFRESH_TOKEN_INVALID;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
