/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as TasksTaskIdIndexRouteImport } from './routes/tasks/$taskId/index'
import { Route as TasksTaskIdHistoryRouteImport } from './routes/tasks/$taskId/history'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdIndexRoute = TasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdHistoryRoute = TasksTaskIdHistoryRouteImport.update({
  id: '/tasks/$taskId/history',
  path: '/tasks/$taskId/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/$taskId/history': typeof TasksTaskIdHistoryRoute
  '/tasks/$taskId': typeof TasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/$taskId/history': typeof TasksTaskIdHistoryRoute
  '/tasks/$taskId': typeof TasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tasks/': typeof TasksIndexRoute
  '/tasks/$taskId/history': typeof TasksTaskIdHistoryRoute
  '/tasks/$taskId/': typeof TasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/tasks'
    | '/tasks/$taskId/history'
    | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/tasks' | '/tasks/$taskId/history' | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/tasks/'
    | '/tasks/$taskId/history'
    | '/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TasksTaskIdHistoryRoute: typeof TasksTaskIdHistoryRoute
  TasksTaskIdIndexRoute: typeof TasksTaskIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/': {
      id: '/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId/history': {
      id: '/tasks/$taskId/history'
      path: '/tasks/$taskId/history'
      fullPath: '/tasks/$taskId/history'
      preLoaderRoute: typeof TasksTaskIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  TasksIndexRoute: TasksIndexRoute,
  TasksTaskIdHistoryRoute: TasksTaskIdHistoryRoute,
  TasksTaskIdIndexRoute: TasksTaskIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
